{% set name = "pyre-extensions" %}
{% set version = "0.0.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5396715f14ea56c4d5fd0a88c57ca7e44faa468f905909edd7de4ad90ed85e55

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  
  # noarch: only build on linux64
  skip: True # [not linux64]

requirements:
  host:
    - python 
    - pip
    - wheel
    - setuptools
  run:
    - python
    - typing_inspect
    - typing-extensions

test:
  imports:
    - pyre_extensions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pyre-check.org
  summary: Type system extensions for use with the pyre type checker
  description: Type system extensions for use with the pyre type checker
  doc_url: https://pyre-check.org/
  dev_url: https://github.com/facebook/pyre-check/tree/main
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Dependency for vllm
    recipe-maintainers:
      - bkreider
  recipe-maintainers:
    - jan-janssen
